import '../../blocks/logic/blocks'
import '../../blocks/color/blocks'
import '../../blocks/math/blocks'
import '../../blocks/text/blocks'
import '../../blocks/time/blocks'
import '../../blocks/loops/blocks'
import '../../blocks/led/blocks'
import '../../blocks/arduino/block'